### ISSUE TITLE
KeyError: "['popv_parent'] not in index"

### ISSUE THREAD

**Issue by ccruizm** [YosefLab/PopV#29]
Good day,

I have been trying to use PopV to train my reference and assign the predictions on the query dataset. When running `annotate_data(adata, save_path=f"{output_folder}/popv_output")` I am having the following error:
```
Initialization is completed.
	Completed 1 / 10 iteration(s).
	Completed 2 / 10 iteration(s).
	Completed 3 / 10 iteration(s).
	Completed 4 / 10 iteration(s).
	Completed 5 / 10 iteration(s).
	Completed 6 / 10 iteration(s).
	Completed 7 / 10 iteration(s).
	Completed 8 / 10 iteration(s).
	Completed 9 / 10 iteration(s).
	Completed 10 / 10 iteration(s).
Found 5000 genes among all datasets
[[0.         0.54671392 0.30050083 ... 0.         0.         0.        ]
 [0.         0.         0.34808013 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.86567164]
 [0.         0.         0.         ... 0.         0.         0.        ]]
Processing datasets (332, 333)
Processing datasets (315, 316)
Processing datasets (314, 316)
Processing datasets (203, 204)
Processing datasets (183, 184)
Processing datasets (227, 228)
Processing datasets (289, 290)
Processing datasets (288, 289)
Processing datasets (8, 9)
Processing datasets (72, 73)
Processing datasets (317, 318)
Processing datasets (184, 187)
Processing datasets (120, 121)
Processing datasets (4, 7)
Processing datasets (221, 222)
Processing datasets (288, 290)
Processing datasets (38, 97)
Processing datasets (122, 123)
Processing datasets (279, 280)
Processing datasets (184, 185)
....
Processing datasets (191, 283)
Processing datasets (254, 292)
Processing datasets (254, 260)
Epoch 121/121: 100%|████████████████████████████████████| 121/121 [03:23<00:00,  1.68s/it, loss=4.19e+03, v_num=1]
INFO     File malignant_predictions/pretrained_model//scvi/model.pt already downloaded                             
INFO     Training for 20 epochs.                                                                                   
Epoch 20/20: 100%|████████████████████████████████████████| 20/20 [00:34<00:00,  1.75s/it, loss=4.41e+03, v_num=1]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[21], line 3
      1 from popv.annotation import annotate_data
----> 3 annotate_data(adata, save_path=f"{output_folder}/popv_output")

File ~/miniconda3/envs/popv/lib/python3.8/site-packages/popv/annotation.py:87, in annotate_data(adata, methods, save_path, methods_kwargs)
     85 if save_path is not None:
     86     prediction_save_path = os.path.join(save_path, "predictions.csv")
---> 87     adata[adata.obs._dataset == "query"].obs[
     88         all_prediction_keys
     89         + [
     90             "popv_prediction",
     91             "popv_prediction_score",
     92             "popv_majority_vote_prediction",
     93             "popv_majority_vote_score",
     94             "popv_parent",
     95         ]
     96     ].to_csv(prediction_save_path)
     98     logging.info(f"Predictions saved to {prediction_save_path}")

File ~/miniconda3/envs/popv/lib/python3.8/site-packages/pandas/core/frame.py:3767, in DataFrame.__getitem__(self, key)
   3765     if is_iterator(key):
   3766         key = list(key)
-> 3767     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3769 # take() does not accept boolean indexers
   3770 if getattr(indexer, "dtype", None) == bool:

File ~/miniconda3/envs/popv/lib/python3.8/site-packages/pandas/core/indexes/base.py:5876, in Index._get_indexer_strict(self, key, axis_name)
   5873 else:
   5874     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 5876 self._raise_if_missing(keyarr, indexer, axis_name)
   5878 keyarr = self.take(indexer)
   5879 if isinstance(key, Index):
   5880     # GH 42790 - Preserve name from an Index

File ~/miniconda3/envs/popv/lib/python3.8/site-packages/pandas/core/indexes/base.py:5938, in Index._raise_if_missing(self, key, indexer, axis_name)
   5935     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   5937 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 5938 raise KeyError(f"{not_found} not in index")

KeyError: "['popv_parent'] not in index"
```
Where might the issue be?
Thanks in advance!

**Comment by cane11** [comment]
It should be fixed in the current main or new PyPI version. Can you check your version and update?

https://github.com/YosefLab/PopV/blob/af1a9d210dace7c442b39c729f03ba7a964cb47a/popv/annotation.py#L78

**Comment by ccruizm** [comment]
I made the installation on a new conda env (PopV v0.3.2), and it still throws me the same error. 
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[19], line 3
      1 from popv.annotation import annotate_data
----> 3 annotate_data(adata, save_path=f"{output_folder}/popv_output")

File /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/popv/lib/python3.8/site-packages/popv/annotation.py:87, in annotate_data(adata, methods, save_path, methods_kwargs)
     85 if save_path is not None:
     86     prediction_save_path = os.path.join(save_path, "predictions.csv")
---> 87     adata[adata.obs._dataset == "query"].obs[
     88         all_prediction_keys
     89         + [
     90             "popv_prediction",
     91             "popv_prediction_score",
     92             "popv_majority_vote_prediction",
     93             "popv_majority_vote_score",
     94             "popv_parent",
     95         ]
     96     ].to_csv(prediction_save_path)
     98     logging.info(f"Predictions saved to {prediction_save_path}")

File /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/popv/lib/python3.8/site-packages/pandas/core/frame.py:3813, in DataFrame.__getitem__(self, key)
   3811     if is_iterator(key):
   3812         key = list(key)
-> 3813     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3815 # take() does not accept boolean indexers
   3816 if getattr(indexer, "dtype", None) == bool:

File /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/popv/lib/python3.8/site-packages/pandas/core/indexes/base.py:6070, in Index._get_indexer_strict(self, key, axis_name)
   6067 else:
   6068     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6070 self._raise_if_missing(keyarr, indexer, axis_name)
   6072 keyarr = self.take(indexer)
   6073 if isinstance(key, Index):
   6074     # GH 42790 - Preserve name from an Index

File /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/popv/lib/python3.8/site-packages/pandas/core/indexes/base.py:6133, in Index._raise_if_missing(self, key, indexer, axis_name)
   6130     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6132 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6133 raise KeyError(f"{not_found} not in index")

KeyError: "['popv_parent'] not in index"
```
I installed it from github. Should I try the pip version? Not sure where the issue is.

**Comment by ccruizm** [comment]
Hello! I am still encountering the same issue now using v0.4.1
```
Epoch 51/51: 100%|█████████████████████████████████████████| 51/51 [03:58<00:00,  4.68s/it, v_num=1, train_loss_step=3.65e+3, train_loss_epoch=3.77e+3]
INFO     File malignant_predictions_braun/pretrained_model//scvi/model.pt already downloaded                       
INFO     Training for 20 epochs.                                                                                   
Epoch 20/20: 100%|█████████████████████████████████████████| 20/20 [01:17<00:00,  3.86s/it, v_num=1, train_loss_step=3.72e+3, train_loss_epoch=3.84e+3]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[32], line 3
      1 from popv.annotation import annotate_data
----> 3 annotate_data(adata, save_path=f"{output_folder}[/popv_output](http://localhost:8886/popv_output)")

File [~/miniconda3/envs/popv/lib/python3.9/site-packages/popv/annotation.py:88](http://localhost:8886/lab/tree/dmg/notebooks/popv/~/miniconda3/envs/popv/lib/python3.9/site-packages/popv/annotation.py#line=87), in annotate_data(adata, methods, save_path, methods_kwargs)
     86 if save_path is not None:
     87     prediction_save_path = os.path.join(save_path, "predictions.csv")
---> 88     adata[adata.obs._dataset == "query"].obs[
     89         all_prediction_keys
     90         + [
     91             "popv_prediction",
     92             "popv_prediction_score",
     93             "popv_majority_vote_prediction",
     94             "popv_majority_vote_score",
     95             "popv_parent",
     96         ]
     97     ].to_csv(prediction_save_path)
     99     logging.info(f"Predictions saved to {prediction_save_path}")

File [~/miniconda3/envs/popv/lib/python3.9/site-packages/pandas/core/frame.py:3813](http://localhost:8886/lab/tree/dmg/notebooks/popv/~/miniconda3/envs/popv/lib/python3.9/site-packages/pandas/core/frame.py#line=3812), in DataFrame.__getitem__(self, key)
   3811     if is_iterator(key):
   3812         key = list(key)
-> 3813     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3815 # take() does not accept boolean indexers
   3816 if getattr(indexer, "dtype", None) == bool:

File [~/miniconda3/envs/popv/lib/python3.9/site-packages/pandas/core/indexes/base.py:6070](http://localhost:8886/lab/tree/dmg/notebooks/popv/~/miniconda3/envs/popv/lib/python3.9/site-packages/pandas/core/indexes/base.py#line=6069), in Index._get_indexer_strict(self, key, axis_name)
   6067 else:
   6068     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6070 self._raise_if_missing(keyarr, indexer, axis_name)
   6072 keyarr = self.take(indexer)
   6073 if isinstance(key, Index):
   6074     # GH 42790 - Preserve name from an Index

File [~/miniconda3/envs/popv/lib/python3.9/site-packages/pandas/core/indexes/base.py:6133](http://localhost:8886/lab/tree/dmg/notebooks/popv/~/miniconda3/envs/popv/lib/python3.9/site-packages/pandas/core/indexes/base.py#line=6132), in Index._raise_if_missing(self, key, indexer, axis_name)
   6130     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6132 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6133 raise KeyError(f"{not_found} not in index")

KeyError: "['popv_parent'] not in index"
```

Is there something wrong with how my data is formatted?

**Comment by canergen** [comment]
Hi, I'm sorry that I haven't seen your previous message. Can you send me your exact code? Is the tutorial working in your hands and is the error only showing in custom data?

**Comment by ccruizm** [comment]
Hello @canergen,

No problem ;)

I am using the following code 
```
from popv.preprocessing import Process_Query

adata = Process_Query(
    query_adata,
    ref_adata,
    query_labels_key=query_labels_key,
    query_batch_key=query_batch_key,
    ref_labels_key=ref_labels_key,
    ref_batch_key=ref_batch_key,
    unknown_celltype_label=unknown_celltype_label,
    save_path_trained_models=output_model_fn,
    cl_obo_folder=False,
    prediction_mode="retrain",
    n_samples_per_label=n_samples_per_label,
    accelerator="cuda",
    compute_embedding=False,
    hvg=5000,
).adata
```

Seems the error happens when using `scvi`. I have tried also to only run other algorithms 
```
algorithms = ["svm_pred", "rf_pred", "onclass_pred", "celltypist_pred", "knn_on_harmony_pred"]
```
But seems it runs them all anyway. I checked, and `Process_Query` does not have the option to assign which algorithms to run. Or am I missing/doing something wrong? I wanted to test if only using a few options that do not include SCANVI/SCVI would work, but it would still re-train with all algorithms.

Hope we can find the reason why this does not work.

P.S. The tutorial data runs since it loads trained models, but I want to train Popv with new references. 

Thanks in advance!

**Comment by canergen** [comment]
There's a typo in the code if using `cl_obo_folder=False`. It has nothing to do with the underlying algorithms. I'm working on a fix and it should be on PyPI end of this week. If you set `save_path=None` in annotate_data the issue should be fixed.

**Comment by ccruizm** [comment]
Yes! It happened when running `annotate_data`. I confirm that setting `save_path=None` avoids the issue. Thanks for the help! 

Thanks for the help!

**Comment by canergen** [comment]
Good to hear. A fix is also released to PyPI (v 0.4.2)
